version: '3'
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
      - ./lib/:/opt/inferno/lib
      - ./:/opt/inferno/
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
      POSTGRES_USER: postgres
      TX_SERVER_URL: https://tx.dev.hl7.org.au/fhir
  inferno-worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
      POSTGRES_USER: postgres
  validator-api:
    # image: infernocommunity/inferno-resource-validator:1.0.52
    image: pavelrozhkov/wrapper:6.3.11
    environment:
      SESSION_CACHE_DURATION: -1
    volumes:
      - ./lib/au_core_test_kit/igs:/home/igs
  nginx:
    image: nginx
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      validator-api:
        condition: service_started
      inferno:
        condition: service_started
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferno
