apiVersion: v1
kind: ConfigMap
metadata:
  name: inferno
  namespace: {{ .Values.namespace }}
data:
  FHIR_RESOURCE_VALIDATOR_URL: {{ default "http://validator-api:3500" .Values.inferno.externalValidatorUrl | quote }}
  REDIS_URL: {{ default "redis://inferno-redis:6379" .Values.inferno.redisUrl | quote }}
  RAILS_ENV: {{ default "production" .Values.inferno.railsEnv | quote }}
