apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
stringData:
  POSTGRES_DB: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
type: Opaque