apiVersion: v1
kind: Service
metadata:
  name: inferno
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 4567
  selector:
    app: inferno-app
