apiVersion: v1
kind: Service
metadata:
  name: inferno-redis
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: inferno-redis
