name: Publish Gem
on:
  push:
    tags:
    - '*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build the gem
        run: |
          gem build au_core_test_kit.gemspec
      - name: Release Gem to GitHub Packages
        uses: jstastny/publish-gem-to-github@v2.4
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         owner: ${{ github.repository_owner }}
